version: "3.8"
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
      - pgadmin
    volumes:
      - ./alembic:/code/alembic
      - ./app:/code/app
      - ./bin:/code/bin
      - ./crud:/code/crud
      - ./database:/code/database
      - ./router:/code/router
      - ./schema:/code/schema
      
  db:
    container_name: postgres_todo_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_todo_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5000:80"

volumes:
  postgres_data: